# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "capybara", "~> 3.15"

gem "os", "~> 1.0"

gem "selenium-webdriver", "~> 3.141"

gem "capybara-screenshot", "~> 1.0"
